### ISSUE TITLE
[error]Could not find exactly one of the appropriate labels on the PR.

### ISSUE THREAD

**Issue by larryjoelane** [zwaldowski/match-label-action#9] opened 2020-06-03 19:50 UTC
I have added a label to a pr named patch and I receive the following error output.

output from action run:

```
Run zwaldowski/match-label-action@v1
  with:
    allowed: major minor patch
  
  env:
    SOLUTION_FILE: MySolution-Main.sln
    NUGET: C:\hostedtoolcache\windows\nuget.exe\5.4.0\x64/nuget.exe
##[error]Could not find exactly one of the appropriate labels on the PR.
```

steps from workflow:
```   
     - name: bump version
        id: bump
        uses: zwaldowski/match-label-action@v1
        with:
          allowed: >
            major
            minor
            patch
      - name: output version
        id: next_version
        uses: zwaldowski/semver-release-action@v1
        with:
          bump: ${{ steps.bump.outputs.match }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by crazy4pi314** [comment] 2020-11-10 19:00
I'm having exactly the same issue, any ideas?
https://github.com/qsharp-community/qram/pull/50

**Comment by zwaldowski** [comment] 2020-11-10 23:50
As this is simply a composition on [`@actions/github`](https://github.com/actions/toolkit/blob/main/packages/github), it’s not clear whether the action is being given the right context from the PR.

@crazy4pi314, would you mind changing your `uses` to `zwaldowski/match-label-action@zwaldowski/debug-issue-9` and turning on debug logs as [described here](<https://github.com/actions/toolkit/blob/main/docs/action-debugging.md#step-debug-logs>)? That should give me a quick path to triaging. Thanks for your patience!

**Comment by unitario** [comment] 2021-07-16 15:43
I'm getting this issue also too. The problem is when you are triggering the action post merge, e.g:

```yaml
on:
  pull_request:
    types: [ closed ]
    branches:
    - master
```

In this case there is no `payload` property for the context so the [`context.payload.pull_request`](https://github.com/zwaldowski/match-label-action/blob/e12bf7e1b3dd7085e50e736470d6adee78a43513/index.js#L7) returns nothing.

Luckily, there is a simple fix for this issue:

```javascript
// Change from this
const labels = pr.labels || []
// To this
const labels = pr.labels || context.labels || []
```

Source: https://github.com/zwaldowski/match-label-action/blob/e12bf7e1b3dd7085e50e736470d6adee78a43513/index.js

You want me to issue a PR or can you do this?

**Comment by unitario** [comment] 2021-07-17 12:38
I'm having this issue as well. The problem is that new lines `\n` are stripped out (only tested in `ubuntu-latest`) causing the `parseAllowed` function to yield incorrect result.

To get around this issue, you need to organize the allowed labels in a comma separated list as opposed to using new lines as illustrated in the documentation.

**Correct**

```yaml
uses: zwaldowski/match-label-action@v2
with:
  allowed: major, minor, patch
```

**Incorrect**

```yaml
uses: zwaldowski/match-label-action@v2
with:
  allowed: >
    major
    minor
    patch
```

**Comment by zwaldowski** [comment] 2021-08-04 02:52
Ah, yes, thanks @unitario. It seems like GitHub's runner doesn't enjoy the `>` syntax. I've updated the README and will investigate on making that syntax work later without regressing #7.

@larryjoelane please see @unitario's note (if you still care about using this of course lol, if not that's fine) and reopen if it's still giving issues. Thanks all!

**Closed as completed by zwaldowski** 2021-08-04 02:52 UTC
